### ISSUE TITLE
dependency problems

### ISSUE THREAD

**Issue by damn-good** [cerker/jwt-example#1]
I've tried to build your project with mvn clean install but I got this error message.
I'm a maven beginer but I have to secure a jersey rest api with oauth and JWT can you please help me.
![failure](https://cloud.githubusercontent.com/assets/8207712/10159241/20ff3c80-668f-11e5-920f-783336d1bfb1.PNG)

**Comment by cerker** [comment]
Adding https://repository.jboss.org/nexus/content/groups/public-jboss as a Maven repo to the pom.xml should help. See https://developer.jboss.org/wiki/MavenGettingStarted-Users
